language: common-lisp

env:
  matrix:
#    - LISP=abcl # Out of memory PermGen space
#    - LISP=allegro # This request cannot be satisfied because you have hit the Allegro CL Free Express heap limit.
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
#    - LISP=clisp # should work with next lisp-unit2 update
#    - LISP=clisp32 # should work with next lisp-unit2 update
#    - LISP=cmucl # /home/travis/.cim/bin/cl: 4: .: Can't open /home/travis/.cim/config/current.3271
    - LISP=ecl

install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi

script:
  - cl -e '(in-package :cl-user)'
       -e '(ql:quickload :clomp)'
       -e '(ql:quickload :clomp-test)'
       -e '(let ((*debugger-hook*
                  (lambda (c h)
                    (declare (ignore c h))
                    (uiop:quit -1))))
             (lisp-unit2:with-failure-debugging-context
                 (lambda ()
                   (clomp-test:run-all-tests))))'
